### ISSUE TITLE
`instanceof` is missing

### ISSUE THREAD

**Issue by sxzz** [unjs/unimport#101]
```ts
el instanceof jQuery ? true : false
```

<img width="847" alt="image" src="https://user-images.githubusercontent.com/6481596/182317856-c99496c6-fda7-4eb6-99b1-34a3ea96b396.png">

identifier `el` and `jQuery` is missing.

**Comment by antfu** [comment]
PR welcome :P

**Comment by sxzz** [comment]
I'm trying... 🧐
