### ISSUE TITLE
Missing dependency `vue/compiler-sfc`?

### ISSUE THREAD

**Issue by TheDutchCoder** [unjs/unimport#120]
I forked this repo in order to hunt down a bug with commented out exports (cc: https://github.com/nuxt/framework/issues/7658) and I noticed after npm installing that there's a dependency on `vue/compiler-sfc`, failing a test. I think it just needs to be `@vue/compiler-sfc`.

Side note (and I can open another issue for this if required), when running `npm run dev` the absolute import test fails as it tries to find `a.vue` which doesn't exist in the project.

**Comment by antfu** [comment]
It works for me. Not sure if it's related to https://github.com/unjs/unimport/issues/121, if so, please use `pnpm`.

**Comment by TheDutchCoder** [comment]
Yeah probably! Thanks!
