### ISSUE TITLE
Support import `dirs` within core

### ISSUE THREAD

**Issue by pi0** [unjs/unimport#213]
### Describe the feature

While working on https://github.com/unjs/nitro/pull/866 i noticed that `dirs` option is only supported for unimport plugin but not unimport core and for generating types, it should be manually integrated with `scanDirExports` and `modifyDynamicImports` (there might be better ways no ideas).

it would be nice if we support it built-in to avoid workaround.

Reproduction: https://stackblitz.com/edit/node-x74ruz?file=index.mjs,utils%2Ftest.ts

(PS: Small unrelated bug i found `generateTypeDeclarations` is not stripping `.ts` from paths resulting into ts issues)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
> Small unrelated bug i found generateTypeDeclarations is not stripping .ts from paths resulting into ts issues

Can you share some examples? It seems to work for me:

https://github.com/unjs/unimport/blob/c910b8c612f9719649c26beb4a257868906e8f26/test/dts.test.ts#L51-L54

**Comment by pi0** [comment]
Thanks for the feat 🚀 

> Can you share some examples? 

Right seems working now on stackblitz. It was strangely happening on nitro will recheck and ping you if happened again.
