### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by ineshbose** [unjs/unimport#227]
### Environment

Cloned repository on Windows 10 22H2 running Node v16.17.0

### Reproduction

Change `playground/composables/nested/index.ts` to

```diff
export default function () {
  return 'from nested composables'
}

+ export * from './bar'
```

### Describe the bug

https://github.com/unjs/unimport/blob/1be4b7baba7af772ea863f2bfe529daa2830bc12/src/scan-dirs.ts#L50-L59

`scanExports` is likely to assume that `filepath` is indeed a filepath while it can be a directory, and so `readFile` fails for the above example where the filepath is `playground/composables/nested/bar` (with no file extension lookup available for it).

### Additional context

Options I can think of:

1. Check if equivalent `/index` exists.

https://github.com/unjs/unimport/blob/1be4b7baba7af772ea863f2bfe529daa2830bc12/src/scan-dirs.ts#L91-L94

```diff
if (existsSync(`${subfilepath}${ext}`)) {
  subfilepath = `${subfilepath}${ext}`
  break
+} else if (existsSync(`${subfilepath}/index${ext}`)) {
+  // 'foo' is a directory
+  subfilepath = `${subfilepath}/index${ext}`
+  break
+}
```

2. I also believed that recursion wouldn't be required, but rather forward the imports. https://github.com/unjs/unimport/pull/216#discussion_r1088354636

https://github.com/unjs/unimport/blob/1be4b7baba7af772ea863f2bfe529daa2830bc12/src/scan-dirs.ts#L104

```diff
- imports.push(...await scanExports(subfilepath, seen))
+ imports.push({ name: '*', from: subfilepath })
```

**Comment by ineshbose** [comment]
Thanks! Would you recommend option 2? (could be more efficient)

**Comment by antfu** [comment]
We need option 1, exporting `*` won't help as we need to know all the export name
