### ISSUE TITLE
Support for plain typescript

### ISSUE THREAD

**Issue by rubiin** [unjs/unimport#252]
### Describe the feature

Correct me if I am wrong, but currently the module can only be used with vuejs, webpack and rollup. I have used it with vuejs in the past and would like to use it on my typescript api projects. 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
It's not coupled with Vue. It works for any JS project with bundlers that [unplugin](https://github.com/unjs/unplugin) supports.
