### ISSUE TITLE
Add eslint-disable and prettier-ignore

### ISSUE THREAD

**Issue by Wyatex** [unjs/unimport#253]
### Describe the feature

I believe these two annotations should be added at the top of the generated d.ts file to prevent conflicts with the project configuration.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Sure, PR welcome

**Comment by Wyatex** [comment]
It seems that the code generation logic is not in unplugin. If i want to implement this feature in unplugin, it might be a bit breaking change.
