### ISSUE TITLE
Auto-import fails when a identifier is the same as a name to be imported

### ISSUE THREAD

**Issue by GoodbyeNJN** [unjs/unimport#270]
### Environment

unimport version: v3.3.0
node.js version: v18.16.0

### Reproduction

```js
import { createUnimport } from 'unimport'

const code = `
{
  const fn = () => {};
};

fn();
`

const { injectImports } = createUnimport({
  imports: [{ name: 'fn', from: 'module' }]
})

const { imports } = await injectImports(code)
console.log(imports)
```

### Describe the bug

https://github.com/unjs/unimport/blob/28cf011fd5b7b0f6f9c3bfd406a9d95a1c30da96/src/context.ts#L247-L256

Before `Remove those already defined`, the value of `occurrenceMap` is `{ size:1, [{ "fn" => 30 }] }`, where `fn` refers to the function which is called outside of the block scope.

While run into the for loop, `strippedCode` will match regexp `/\b(?:const|let|var)\s+?(\[.*?\]|\{.*?\}|.+?)\s*?[=;\n]/gs`, and matching result is `[ "const fn =", "fn" ]`, where `fn` refers to the function defined inside the block scope. So `occurrenceMap.delete(identifier)` will be executed, `occurrenceMap` will be cleared, and finally no `import` statement will be prepended to the code.

Seems in this situation, regexp matching is not enough, and lexical analysis may be needed?

**Comment by lehni** [comment]
We've also encountered this… I wonder if the only way to make `unimport` work reliably would be to stop using regexps and use AST parsing and processing instead?

**Comment by antfu** [comment]
Yeah, this is indeed sometimes impossible to fix with regex. I think that makes sense to introduce an optional mode to do full parsing.

**Comment by antfu** [comment]
Created #304 to track on that.

**Comment by antfu** [comment]
https://github.com/unjs/unimport/issues/304 is implemented, try with `parser: 'acorn'`
