### ISSUE TITLE
Question: what is the purpose of `defineUnimportPreset`?

### ISSUE THREAD

**Issue by noahgregory-basis** [unjs/unimport#310]
I was looking through the Nuxt source code and saw it uses `defineUnimportPreset` in [some places](https://github.com/nuxt/nuxt/blob/d26822f/packages/nuxt/src/imports/presets.ts#L2). However, upon reading the source code here, it seems the `defineUnimportPreset` does nothing but [return the passed in parameter](https://github.com/unjs/unimport/blob/d9bb922/src/utils.ts#L8-L10). It doesn't even re-type it. What is the use of this function? Does it cause some obscure side effect that is desired, is it a "functional" way of ensuring the type of the preset is correct, or is it something else? If it is a type thing, why use that pattern over simply exporting the type information?

**Comment by antfu** [comment]
https://antfu.me/posts/type-your-config
