### ISSUE TITLE
Support for unjs stack in presets

### ISSUE THREAD

**Issue by shinGangan** [unjs/unimport#313]
## Context

I am developing a web application in Nuxt. So, unjs/unimport has been very helpful. Thank you for developing it.

I often use the following two for developing web applications in Nuxt.

- unjs/consola: Logger for Nuxt Server
- unjs/h3: use in Nuxt Server

I would like to be able to use unjs stack from unimport presets, not only these two.

## Design

There are two possible designs

1. add `unjs/*` to each preset.

    - **Advantage**: easier for users to find from presets.
    - **Disadvantage**: presets will be bloated by the number of unjs stacks -> more than 50 files will make `presets/` harder to maintain 

    ### Example
    - consola -> `presets/consola.ts`
    - h3 -> `presets/h3.ts`.

```ts
presets: [
  {
    from: "consola",
    imports: [ "consola" ]
  },
  {
    from: "h3",
    imports: [ "EventHandler", "EventHandlerRequest", "readBody", "getValidatedQuery" ]
  }
]
```

2. create unjs presets.

    This would be similar to the unjs/unkit philosophy.

    - **Advantage**: no impact on users even if unjs stack is increased
    - **Disadvantage**: not sure what is available in unjs presets. You need to check `presets/unjs.ts` to see what is available.

    
    ### Example

    - `presets/unjs.ts`.

```ts
presets: [
  {
    from: "unjs",
    imports: [ "consola", "EventHandler" ]
  }
]
```

### My opinion

I would implement proposal 1 and move to proposal 2 if the number of unjs stacks required by users increases too much.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by shinGangan** [comment]
Hi @antfu .

I would appreciate your review when you have time. 🙏
If this policy is acceptable, I will respond and create a Pull Request.

**Comment by antfu** [comment]
I wonder if https://github.com/unjs/unimport#exports-auto-scan could cover your usage case already?

**Comment by shinGangan** [comment]
@antfu , thanks.

I had missed the `auto scan`. Thanks for letting me know.
It would be nice if Nuxt's default auto-import included unjs stacks, but I think the number of users who would be happy with the default might be limited.

Besides Nuxt, I often use h3 + consola + unjs stack for Hono, Azure Functions, Lambda, etc.
I often wish I could do auto-imports unjs stack in Lambda and etc as I develop with Nuxt (because Nuxt developing experience with auto-imports was great).

Is a `custom preset` or `auto scan` the best practice in this case as well, rather than importing from `presets`?

**Comment by pi0** [comment]
Thanks for the suggestion dear @shinGangan. The idea seems intriguing but I tend to agree with @antfu with auto scan feature, it might be much more sensible since it requires less maintenance. I tried [unkit](https://github.com/unjs/unkit/) long ago in hope of achieving the same but more and more I think this can be tricky how we can even define unjs and what is in and what is not. Focusing on having better auto scan (maybe a preset builder util?) would be the best way to go IMO.

**Comment by shinGangan** [comment]
@pi0 , thanks for your comments.

I have tried the 'auto scan' as you suggested and am happy with it as well.
I think 'custom presets' and 'auto scan' are sufficient for Nuxt use.

> I tried unkit long ago in hope of achieving the same but more and more I think this can be tricky how we can even define unjs and what is in and what is not.

I have the same experience here.
I installed `unkit/http` and tried it, but I didn't know what was in it, so I explicitly installed `unjs/h3`.

**Comment by shinGangan** [comment]
Thank you for your comments, @antfu , @pi0 .

I stand by @pi0 's comment. Therefore, this Issue is no longer needed.
Please feel free to close it at any time.

I enjoyed discussing this with you both.
If there is something good for unjs, Nuxt, I will continue to suggest it.
