### ISSUE TITLE
Support for vueuse breakpoints

### ISSUE THREAD

**Issue by zekunjin** [unjs/unimport#327]
### Describe the feature

Support auto import vueuse breakpoints like `breakpointsTailwind`.

In `useBreakpoints` API, a breakpoint config is required. Auto import of some commonly used breakpoints would be very convenient.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
https://github.com/unjs/unimport/pull/328#issuecomment-1952297545
