### ISSUE TITLE
Auto-Import vue directives

### ISSUE THREAD

**Issue by manniL** [unjs/unimport#334]
### Describe the feature

Hey all 👋🏻

It would be great if Vue directives could be auto-imported when being used.

Example code which should "magically work":

In the component: 
```vue
<template>
  <div v-my-directive>Hey</div>
</template>
```

Auto-imported file:
```ts
export const vMyDirective = {/*...*/}
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Sounds good if you managed to implement it :)

**Comment by manniL** [comment]
I'll look into how and might ping you if I have questions 👀
