### ISSUE TITLE
Class type is not automatically imported (TS2749)

### ISSUE THREAD

**Issue by AntoninRousset** [unjs/unimport#385]
### Environment

unimport@3.13.1
vue-tsc@2.1.10
nuxt@3.13.2

### Reproduction

https://stackblitz.com/edit/github-68jxaq-ygowgd

`npm install && npx nuxi typecheck`

### Describe the bug

I expect the type of the class to be auto imported just like the class value is. Instead typescript complains that the type is not defined.

### Additional context

https://github.com/unjs/unimport/issues/318#issuecomment-2446409566

### Logs

```sh
TS2749: 'User' refers to a value, but is being used as a type here. Did you mean 'typeof User'?
```

**Comment by orimay** [comment]
Same issue

**Comment by orimay** [comment]
@antfu, thank you for the fix! But there's one more edge case that fails to work:
```typescript
export const ScheduleRuleType = {
  ONCE: 'ONCE',
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY_BY_WEEKDAYS: 'MONTHLY_BY_WEEKDAYS',
  MONTHLY_BY_MONTHDAYS: 'MONTHLY_BY_MONTHDAYS',
  YEARLY: 'YEARLY',
} as const;
export type ScheduleRuleType =
  (typeof ScheduleRuleType)[keyof typeof ScheduleRuleType];
```

**Comment by noootwo** [comment]
> @antfu, thank you for the fix! But there's one more edge case that fails to work:
> 
> ```ts
> export const ScheduleRuleType = {
>   ONCE: 'ONCE',
>   DAILY: 'DAILY',
>   WEEKLY: 'WEEKLY',
>   MONTHLY_BY_WEEKDAYS: 'MONTHLY_BY_WEEKDAYS',
>   MONTHLY_BY_MONTHDAYS: 'MONTHLY_BY_MONTHDAYS',
>   YEARLY: 'YEARLY',
> } as const;
> export type ScheduleRuleType =
>   (typeof ScheduleRuleType)[keyof typeof ScheduleRuleType];
> ```

@antfu I found here dedupe the imports for the same name variable and type https://github.com/unjs/unimport/blob/631f833651af5ca04ab01af84c182a19b7edadce/src/node/scan-dirs.ts#L96-L109
