### ISSUE TITLE
`utils/*/index.ts` Not Working Since v3.14

### ISSUE THREAD

**Issue by sumomo015** [unjs/unimport#404]
### Environment

nodejs: 22.12.0
typescript: 5.7.2
unimport: 3.14.4
vite: 6.0.3

### Reproduction

https://github.com/sumomo015/unimport-test/tree/main

Steps to Reproduce:
1. `pnpm install`
2. `pnpm postinstall`
3. `pnpm typecheck`

It working at v3.13.4
https://github.com/sumomo015/unimport-test/tree/3.13.4

### Describe the bug

`utils/*/index.ts` not Working, and the following errors are encountered.

```
src/main.ts:2:31 - error TS2304: Cannot find name 'TEXT_FILE_PATH'.

2 console.log("TEXT_FILE_PATH", TEXT_FILE_PATH);
```

### Additional context

I first found that `utils/*/index.ts` didn't work in Nuxt, so I came here

### Logs

```sh
> unimport-test@1.0.0 typecheck /Users/sumomo/github/unimport-test
> tsc --noEmit

src/main.ts:2:31 - error TS2304: Cannot find name 'TEXT_FILE_PATH'.

2 console.log("TEXT_FILE_PATH", TEXT_FILE_PATH);
                                ~~~~~~~~~~~~~~


Found 1 error in src/main.ts:2
```

**Comment by noootwo** [comment]
A workaround:
```ts
{
  dirs: ["./utils/*/*"],
  dirsScanOptions: {
    filePatterns: ["index.ts"],
  },
  dts: true,
}
```

**Comment by noootwo** [comment]
> Yeah, let's revert that behavior change to not break the existing users. @noootwo Would you like to initiate the PR? Thanks!

Sure, I'll make a PR.
