### ISSUE TITLE
Support auto import inside Vue template

### ISSUE THREAD

**Issue by antfu** [unjs/unimport#6]
https://github.com/antfu/unplugin-auto-import/issues/115

Maybe for Svelte as well in the future

**Comment by pi0** [comment]
Hi @antfu. Is there any update on this or a blocker to implement?

**Comment by antfu** [comment]
It's a bit tricky to do, but I got an idea and I think it could be possible. Since it could like quite some time, I guess it's better to wait until we release RC?
